dewsweeper/boi/urls.py
from django.conf.urls import url

from . import views

app_name = 'boi'
urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^banzuke/?$', views.BanzukeView.as_view(), name='banzuke'),
  url(r'^banzuke/(?P<pk>[0-9]+)/$',
      views.ProfileView.as_view(),
      name='profile'),
  url(r'^dewsweeper/$', views.dewsweeper_view, name='dewsweeper'),
  url(r'^dewsweeper/auto/$', views.dewsweeper_automated_view,
      name='dewsweeper_automated'),
  url(r'^draftregistration/$', views.draft_registration_view,
      name='draft_registration'),
  url(r'^manage/?$', views.SquadronManagementIndexView.as_view(),
      name='mgmt_index'),
  url(r'^manage/(?P<oyakata_id>[0-9]+)/$', views.squadron_management_view,
      name='mgmt'),
  url(r'^matchups/$', views.MatchupsView.as_view(), name='matchups'),
  url(r'^monkeylist/$', views.monkey_list_view, name='monkey_list'),
  url(r'^monkeysubmit/auto/$', views.monkey_automated_management_view,
      name='monkeysubmit_automated'),
  url(r'^recordbanzuke/$', views.record_banzuke_view, name='record_banzuke'),
  url(r'^registerplayers/$', views.register_players_view,
      name='register_players'),
  url(r'^resultsindex/$', views.ResultsIndexView.as_view(),
      name='results_index'),
  url(r'^results/$', views.ResultsView.as_view(), name='results'),
  url(r'^scheduleregistration/$', views.schedule_registration_view,
      name='schedule_registration'),
  url(r'^standings/$', views.StandingsView.as_view(), name='standings'),
  url(r'^suicide/$', views.SuicideStandingsView.as_view(), name='suicide'),
  url(r'^utils/$', views.UtilsView.as_view(), name='utils'),
  url(r'^waivers/$', views.waivers_view, name='waivers'),
  url(r'^winlossmatrix/$', views.WinLossMatrixView.as_view(),
      name='winlossmatrix'),
]

dewsweeper/dewsweeper/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda _: HttpResponseRedirect('boi/')),
    url(r'^boi/', include('boi.urls')),
    url(r'^admin/', admin.site.urls),
]

dewsweeper/boi/forms.py
from django import core
from django import forms

from .boi_config import LINEUP_SIZE, TOTAL_DAYS
from .models import OzumoBanzukeEntry
from .utils import get_current_basho_id


class StartingRikishiField(forms.MultipleChoiceField):
  def validate(self, value):
    if len(value) != LINEUP_SIZE:
      raise core.exceptions.ValidationError(
        'Please select %s rikishi.' % LINEUP_SIZE)

    super(StartingRikishiField, self).validate(value)


class ActiveDayField(forms.TypedChoiceField):
  def validate(self, value):
    super(ActiveDayField, self).validate(value)
    if int(value) < 1 or int(value) > TOTAL_DAYS:
      raise core.exceptions.ValidationError(
        'Please select a valid day. (%s, %s)' % (value, type(value))
      )


class SquadronManagementForm(forms.Form):
  pre_trash_talk = forms.CharField(widget=forms.Textarea,
                                   required=False)
  starting_rikishi = StartingRikishiField(
    widget=forms.CheckboxSelectMultiple,
  )
  suicide_pick = forms.ModelChoiceField(queryset=None, empty_label=None,
                                        required=False)
  post_trash_talk = forms.CharField(widget=forms.Textarea,
                                    required=False)
  active_day = ActiveDayField(coerce=int, empty_value=0)

  def __init__(self, *args, **kwargs):
    rikishi = kwargs.pop('rikishi')
    prev_suicide_picks = kwargs.pop('prev_suicide_picks', [])
    suicide_pool_active = kwargs.pop('suicide_pool_active', False)
    day = kwargs.pop('day')
    basho_id = get_current_basho_id()
    self.base_fields['starting_rikishi'].empty_label = None
    super(SquadronManagementForm, self).__init__(*args, **kwargs)

    self.fields['starting_rikishi'].choices = [
      (int(r.rikishi.id), r.rikishi.shikona_for_basho(basho_id))
      for r in rikishi
    ]

    self.fields['suicide_pick'].queryset = OzumoBanzukeEntry.objects.filter(
      basho_id=basho_id
    ).exclude(
      rikishi_id__in=prev_suicide_picks
    ).order_by('rank')

    if not suicide_pool_active:
      self.fields['suicide_pick'].disabled = True

    self.fields['active_day'].choices = [
      (d, d) for d in xrange(max(day, 1), TOTAL_DAYS + 1)
    ]

    self.fields['pre_trash_talk'].widget.attrs['rows'] = 10
    self.fields['pre_trash_talk'].widget.attrs['cols'] = 80
    self.fields['post_trash_talk'].widget.attrs['rows'] = 10
    self.fields['post_trash_talk'].widget.attrs['cols'] = 80


class RegisterPlayersForm(forms.Form):

  def __init__(self, *args, **kwargs):
    old_basho_squadrons = kwargs.pop('old_basho_squadrons', [])

    super(RegisterPlayersForm, self).__init__(*args, **kwargs)

    for i, squadron in enumerate(old_basho_squadrons):
      field_name = 'player{i}'.format(i=i)
      self.fields[field_name] = forms.CharField(
        label=squadron.oyakata.real_name,
        initial=squadron.shikona,
        min_length=1,
        max_length=100,
      )
      self.fields[field_name].widget.attrs['size'] = 50


class MonkeyListForm(forms.Form):
  partial_draft_results = forms.CharField(
    widget=forms.Textarea, required=True)

  def __init__(self, *args, **kwargs):
    super(MonkeyListForm, self).__init__(*args, **kwargs)

    self.fields['partial_draft_results'].widget.attrs['rows'] = 25
    self.fields['partial_draft_results'].widget.attrs['cols'] = 80


class DraftRegistrationForm(forms.Form):
  draft_results = forms.CharField(widget=forms.Textarea, required=True)

  def __init__(self, *args, **kwargs):
    super(DraftRegistrationForm, self).__init__(*args, **kwargs)

    self.fields['draft_results'].widget.attrs['rows'] = 25
    self.fields['draft_results'].widget.attrs['cols'] = 80


class ScheduleRegistrationForm(forms.Form):
  schedule = forms.CharField(widget=forms.Textarea, required=True)

  def __init__(self, *args, **kwargs):
    super(ScheduleRegistrationForm, self).__init__(*args, **kwargs)

    self.fields['schedule'].widget.attrs['rows'] = 40
    self.fields['schedule'].widget.attrs['cols'] = 80


class WaiversForm(forms.Form):
  waivers = forms.CharField(widget=forms.Textarea, required=True)

  def __init__(self, *args, **kwargs):
    super(WaiversForm, self).__init__(*args, **kwargs)

    self.fields['waivers'].widget.attrs['rows'] = 20
    self.fields['waivers'].widget.attrs['cols'] = 60

dewsweeper/boi/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from collections import defaultdict
import logging

from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, HttpResponseForbidden, \
  HttpResponseRedirect, HttpResponseServerError
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.views import generic

from .boi_config import CRON_HEADER
from .boi_config import NUM_PLAYERS, TOTAL_DAYS
from .boi_config import KACHI_BRACKET_BOUND, KUWAHIRA_BRACKET_BOUND
from .boi_config import LAST_DAY_OF_REG_SEASON
from .boi_config import LINEUP_SIZE
from .boi_config import MONKEY_SHIKONA
from .boi_config import SQUADRON_SIZE
from .boi_config import SUICIDE_LAST_STRIKE, SUICIDE_NO_SELECTION_STR
from .boi_config import SUICIDE_WIN_BY_FUSEN_STR

from .draft import DraftRegistrar

from .emailers import LineupEmailer

from .exceptions import BoiException

from .forms import DraftRegistrationForm
from .forms import MonkeyListForm
from .forms import RegisterPlayersForm
from .forms import ScheduleRegistrationForm
from .forms import SquadronManagementForm
from .forms import WaiversForm

from .models import BashoSquadron
from .models import Bout
from .models import LineupEntry
from .models import Oyakata
from .models import OzumoBanzukeEntry
from .models import OzumoBout
from .models import Rikishi
from .models import SquadronMember
from .models import SuicidePoolEntry

from .monkey import MonkeyLineupSubmitter
from .monkey import MonkeyListGenerator

from .scheduling import ScheduleRegistrar

from .scoring import DewsweeperProcessor
from .scoring import SquadronSorter

from .utils import get_basho_full_name
from .utils import get_current_basho_id

from .view_utils import check_for_dewsweeper_readiness
from .view_utils import cmp_squadrons_suicide
from .view_utils import get_basho_id_from_request
from .view_utils import get_day_from_request
from .view_utils import get_current_day
from .view_utils import get_opponent
from .view_utils import get_ozumo_banzuke
from .view_utils import get_previous_basho_squadrons
from .view_utils import get_rikishi_profile
from .view_utils import is_basho_active
from .view_utils import is_suicide_pool_active

from .waivers import WaiversProcessor


class IndexView(generic.TemplateView):
  template_name = 'boi/index.html'

  def get_context_data(self, **kwargs):
    context = super(IndexView, self).get_context_data(**kwargs)
    context['basho_full_name'] = get_basho_full_name(get_current_basho_id())
    return context


class BanzukeView(generic.ListView):
  template_name = 'boi/banzuke.html'
  context_object_name = 'squadron_rows'

  def get_queryset(self):
    """Return all oyakata."""
    results = []
    basho_id = get_current_basho_id()
    while len(results) != NUM_PLAYERS / 2 and basho_id >= 450:
      squadrons = BashoSquadron.objects.filter(
        basho_id=basho_id
      ).order_by('rank')
      results = [(squadrons[i], squadrons[i + 1])
                 for i in xrange(0, len(squadrons), 2)]
      basho_id -= 1

    return results


class ProfileView(generic.DetailView):
  template_name = 'boi/profile.html'
  context_object_name = 'profile'
  model = Oyakata


class SquadronManagementIndexView(generic.ListView):
  template_name = 'boi/mgmt_index.html'
  context_object_name = 'squadrons'

  def get_queryset(self):
    """Return all squadrons for the current basho."""
    return BashoSquadron.objects.filter(
      basho_id=get_current_basho_id()
    ).order_by('shikona')


def squadron_management_view(request, oyakata_id):
  basho_id = get_current_basho_id()
  day = get_current_day()

  oyakata = get_object_or_404(Oyakata, id=oyakata_id)

  basho_squadron = BashoSquadron.objects.filter(
    basho_id=basho_id
  ).filter(
    oyakata=oyakata
  ).get()

  if day > TOTAL_DAYS:
    return render(request, 'boi/mgmt.html', {
      'basho_squadron': basho_squadron,
      'form': None,
      'has_lineup': True,
    })

  squadron_members = basho_squadron.squadron_members
  has_lineup = (len(squadron_members) == SQUADRON_SIZE)

  opponent = get_opponent(oyakata, basho_id, day)

  if opponent:
    # See if a lineup has already been submitted
    opponent_info = LineupEntry.objects.filter(
      basho_id=basho_id,
      day=day,
      oyakata=opponent,
    ).order_by('order')

    # If opponent has no lineup, use entire squadron roster
    if not opponent_info:
      opponent_info = SquadronMember.objects.filter(
        basho_id=basho_id,
        oyakata=opponent,
        is_active=True,
      ).order_by('selection_order')
  else:
    opponent_info = None

  prev_suicide_picks = SuicidePoolEntry.objects.filter(
    basho_id=basho_id,
    oyakata=oyakata,
    day__lt=day,
  ).values('rikishi_id')
  suicide_pool_active = is_suicide_pool_active(basho_id)

  form = SquadronManagementForm(request.POST or None,
                                rikishi=squadron_members,
                                prev_suicide_picks=prev_suicide_picks,
                                suicide_pool_active=suicide_pool_active,
                                day=get_current_day())

  if form.is_valid():
    with transaction.atomic():
      selected_day = form.cleaned_data.get('active_day')

      # First, delete any pre-existing lineup entries
      LineupEntry.objects.filter(
        oyakata=oyakata,
        basho_id=basho_id,
        day=selected_day,
      ).delete()

      selected_lineup = [Rikishi.objects.get(id=r)
                         for r
                         in form.cleaned_data.get('starting_rikishi', [])]

      new_lineup_entries = []
      for n, rikishi in enumerate(selected_lineup):
        new_lineup_entries.append(LineupEntry.objects.create(
          oyakata=oyakata,
          rikishi=rikishi,
          basho_id=basho_id,
          day=selected_day,
          order=n + 1
        ))

      suicide_pick = form.cleaned_data.get('suicide_pick')

      if suicide_pick:
        # First, map the OzumoBanzukeEntry to a Rikishi
        suicide_rikishi = suicide_pick.rikishi

        # Then, remove old suicide pick, if any
        SuicidePoolEntry.objects.filter(
          oyakata=oyakata,
          basho_id=basho_id,
          day=selected_day,
        ).delete()

        # Finally, create new SuicidePoolEntry
        SuicidePoolEntry.objects.create(
          oyakata=oyakata,
          rikishi=suicide_rikishi,
          basho_id=basho_id,
          day=selected_day,
        )

      lineup_emailer = LineupEmailer(
        new_lineup_entries,
        suicide_pick,
        form.cleaned_data.get('pre_trash_talk'),
        form.cleaned_data.get('post_trash_talk'),
        basho_squadron,
        selected_day,
      )
      lineup_emailer.send_email()

      return HttpResponseRedirect(
        reverse('boi:matchups') + '?b={0}&d={1}'.format(
          basho_id, selected_day))

  return render(request, 'boi/mgmt.html', {
    'basho_squadron': basho_squadron,
    'form': form,
    'has_lineup': has_lineup,
    'opponent': opponent,
    'opponent_info': opponent_info,
    'suicide_pool_active': suicide_pool_active,
  })


def monkey_automated_management_view(request):
  # First, make sure this is run by a cron job
  if request.META.get(CRON_HEADER) is None:
    logging.error(
      'Someone attempted to run the Monkey outside of a cron job')
    return HttpResponseForbidden(
      'Cannot run the Monkey outside of a cron job')

  # Make sure basho is active
  basho_id = get_basho_id_from_request(request)
  if not is_basho_active(basho_id):
    msg = 'Monkey exiting because {0} is inactive'.format(
      get_basho_full_name(basho_id))
    logging.info(msg)
    return HttpResponse(msg)

  day = get_day_from_request(request, basho_id=basho_id)
  send_email = bool(request.GET.get('send_email', True))

  # Make sure Monkey has a BashoSquadron
  basho_squadron = BashoSquadron.objects.filter(
    basho_id=basho_id,
    shikona=MONKEY_SHIKONA,
  ).first()
  if not basho_squadron:
    msg = 'Monkey exiting because no BashoSquadron exists for {0}'.format(
      get_basho_full_name(basho_id))
    logging.info(msg)
    return HttpResponse(msg)

  # Make sure Monkey has a squadron to choose from
  squadron_members_count = SquadronMember.objects.filter(
    basho_id=basho_id,
    oyakata=basho_squadron.oyakata,
    is_active=True,
  ).count()
  if squadron_members_count != SQUADRON_SIZE:
    msg = ('Monkey exiting because of incorrect squadron size '
           '({0}, expected {1}) for {2}').format(
      squadron_members_count,
      SQUADRON_SIZE,
      get_basho_full_name(basho_id))
    logging.info(msg)
    return HttpResponse(msg)

  # Make sure Monkey doesn't already have a lineup in
  preexisting_lineup_entry_count = LineupEntry.objects.filter(
    oyakata=basho_squadron.oyakata,
    basho_id=basho_id,
    day=day,
  ).count()
  if preexisting_lineup_entry_count >= LINEUP_SIZE:
    msg = ('Monkey exiting because lineup already exists '
           'for {0}, Day {1}').format(
      get_basho_full_name(basho_id), day)
    logging.info(msg)
    return HttpResponse(msg)

  # Check if we need to generate a suicide pick
  include_suicide = (is_suicide_pool_active(basho_id) and
                     basho_squadron.suicide_still_alive)

  monkey_lineup_submitter = MonkeyLineupSubmitter(
    basho_id, day, include_suicide, send_email)
  monkey_lineup_entries = monkey_lineup_submitter.submit_lineup()

  msg = 'Monkey successfully submitted for {0} Day {1}'.format(
    get_basho_full_name(basho_id), day)
  logging.info(msg)
  msg2 = 'Monkey Lineup:\n{0}'.format(
    '\n'.join([le.rikishi.shikona_for_basho(basho_id)
               for le in monkey_lineup_entries]))
  logging.info(msg2)
  return HttpResponse(u'{0}\n{1}'.format(msg, msg2))


class ResultsIndexView(generic.TemplateView):
  template_name = 'boi/resultsindex.html'
  context_object_name = 'context'

  def get_context_data(self, **kwargs):

dewsweeper/boi/templates/boi/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'boi/boi.css' %}" />
{% block special_css %}
{% endblock %}

<head>
  {% block head %}
  {% endblock %}
</head>

<body>

<img class="logo" src="{% static 'boi/images/basho_logo.gif' %}"><br />

<div class="content container center">
  {% block content %}
  {% endblock %}
</div>

<div class="center">
  <a class="backtomainpage" href="{% url 'boi:index' %}">Back to main page</a>
</div>

</body>

dewsweeper/boi/templates/boi/dewsweeper.html
{% extends 'boi/base.html' %}
{% load static %}

{% block head %}
  <title>Dewsweeper - Basho of Imagination</title>
{% endblock %}

{% block content %}
<body>
{% if error_msg %}
  <span class="normal">{{ error_msg|linebreaksbr }}</span>
{% else %}
  <span class="normal">Ready to sweep the dew!</span>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" id="basho_id" name="basho_id" value="{{ basho_id }}" />
    <input type="hidden" id="day" name="day" value="{{ day }}" />
    <input type="hidden" id="confirm" name="confirm" value="true" />
    <input type="submit" name="SubmitButton" value="Sweep the Dew!" id="SubmitButton"/>
  </form>
{% endif %}
</body>
{% endblock %}

dewsweeper/boi/templates/boi/draftregistration.html
{% extends 'boi/base.html' %}
{% load static %}

{% block special_css %}
<link rel="stylesheet" type="text/css" href="{% static 'boi/draftregistration.css' %}" />
{% endblock %}

{% block head %}
  <title>Draft Registration - Basho of Imagination</title>
{% endblock %}

{% block content %}
<span class="style4">Draft Registration Utility</span>
<div class="ContentWrapper">
{% if status %}<p><span id="StatusLabel">{{ status }}</span></p>{% endif %}
<p class="normal">
  To use, paste in the results from the Google Sheet into this box.
</p>
<p>
<form method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <p>
    <div class="fieldWrapper">
      {{ form.draft_results.errors }}
      {{ form.draft_results }}
    </div>
  </p>
  <p>
    <input type="submit" class="button" value="Submit" />
  </p>
</form>
</p>
</div>
{% endblock %}

dewsweeper/boi/templates/boi/matchups.html
{% extends 'boi/base.html' %}
{% load static %}
{% load boi_extras %}

{% block special_css %}
<link rel="stylesheet" type="text/css" href="{% static 'boi/matchups.css' %}" />
{% endblock %}

{% block head %}
  <title>Tonight's Matchups - Basho of Imagination</title>
{% endblock %}

{% block content %}
{% if matchups %}
<span class="style1">Tonight's Matchups - Day {{ day }}</span>
<table cellspacing="40">
  {% for m in matchups %}
  <tr>
    <td><img src="{{ m.oyakata1.image_url }}" /></td>
    <td><img src="{% static 'boi/images/versus.gif' %}" /></td>
    <td><img src="{{ m.oyakata2.image_url }}" /></td>
  </tr>
  <tr>
    <td align="center" valign="top">
      <b>{{ m.oyakata1_shikona }}</b> ({{ m.oyakata1.rank_short_str }}) {{ m.oyakata1_basho_record.wins }}-{{ m.oyakata1_basho_record.losses }}-{{ m.oyakata1_basho_record.draws }}<br />
      {% for lineup_entry in m.oyakata1_lineup %}
      {{ lineup_entry.rikishi.most_recent_shikona }}<br />
      {% endfor %}
    </td>
    <td></td>
    <td align="center" valign="top">
      <b>{{ m.oyakata2_shikona }}</b> ({{ m.oyakata2.rank_short_str }}) {{ m.oyakata2_basho_record.wins }}-{{ m.oyakata2_basho_record.losses }}-{{ m.oyakata2_basho_record.draws }}<br />
      {% for lineup_entry in m.oyakata2_lineup %}
      {{ lineup_entry.rikishi.most_recent_shikona }}<br />
      {% endfor %}
    </td>
  </tr>
  {% endfor %}
</table>
{% else %}
<span class="style3">No active basho.</span>
{% endif %}
{% endblock %}

dewsweeper/boi/templates/boi/mgmt.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'boi/mgmt.css' %}" />

<head>
  <title>Squadron Management - Basho of Imagination</title>

  <script type="text/javascript">
    <!--
      function checkForm(form)
      {
        var submitButton = document.getElementById("submitButton");
        submitButton.disabled = true;
        return true;
      }
    //-->
  </script>
</head>

<body>
  <img src="{{ basho_squadron.oyakata.image_url }}" /><br />
  <span class="welcome">Welcome, {{ basho_squadron.oyakata.shikona_for_current_basho }}</span><br />
  {% if has_lineup %}
    {% if form %}
    <form action="{% url 'boi:mgmt' basho_squadron.oyakata.id %}" method="post" onsubmit="return checkForm(this);">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="fieldWrapper">
        {{ form.pre_trash_talk.errors }}
        <label for="{{ form.pre_trash_talk.id_for_label }}">Text to appear before rikishi selections:</label><br />
        {{ form.pre_trash_talk }}
      </div>
      <div class="fieldWrapper">
        <table class="squadrontable">
          <tr>
            <td>
              <br />
              {{ form.starting_rikishi.errors }}
              {{ form.starting_rikishi }}
            </td>
            {% if opponent %}
            <td class="opponentcell">
              <u>{{ opponent.shikona_for_current_basho }}</u><br />
              {% for r in opponent_info %}
              {{ r.rikishi.most_recent_shikona }}<br />
              {% endfor %}
            </td>
            {% endif %}
          </tr>
        </table>
      </div>
      <div class="fieldWrapper">
        {% if not suicide_pool_active %}
        <i>The suicide pool has ended for this basho.</i><br />
        {% elif not basho_squadron.suicide_still_alive %}
        <i>You have been eliminated from the suicide pool.</i><br />
        {% else %}
        {{ form.suicide_pick.errors }}
        <label for="{{ form.suicide_pick.id_for_label }}">Suicide pick:</label> {{ form.suicide_pick }}
        {% endif %}
      </div>
      <div class="fieldWrapper">
        {{ form.post_trash_talk.errors }}
        <label for="{{ form.post_trash_talk.id_for_label }}">Text to appear after rikishi selections:</label><br />
        {{ form.post_trash_talk }}
      </div>
      <p class="button_p">
        <input type="submit" class="button" value="Submit" name="submitButton" id="submitButton"/>
      </p>
      <p class="button_p">
        <span class="style3">
          {{ form.active_day.errors }}
          <label for="{{ form.active_day.id_for_label }}">Day:</label>
        </span>
        {{ form.active_day }}
      </p>
    </form>
    {% else %}
    <span class='style3'>There is no active basho.</span>
    {% endif %}
  {% else %}
  <p><span class='style3'>No squadron available for this oyakata.</span></p>
  {% endif %}
</body>

dewsweeper/boi/templates/boi/mgmt_index.html
{% extends 'boi/base.html' %}
{% load static %}
{% load boi_extras %}

{% block special_css %}
<link rel="stylesheet" type="text/css" href="{% static 'boi/mgmt_index.css' %}" />
{% endblock %}

{% block head %}
  <title>Squadron Management - Basho of Imagination</title>
{% endblock %}

{% block content %}
<span class="title">Squadron Management</span><br /><br />

<span class="subtitle">Select your squadron to manage starters</span><br /><br />

<table>
{% for squadron in squadrons %}
<tr>
  <td><a href="{% url 'boi:mgmt' squadron.oyakata.id %}">{{ squadron.shikona }}</a></td>
</tr>
{% endfor %}
</table>
<br /><br />
{% endblock %}

dewsweeper/boi/templates/boi/registerplayers.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'boi/boi.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'boi/registerplayers.css' %}" />

<body>
  <form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <table id="RegistrationTable">
      {% for field in form.visible_fields %}
      <tr>
        <td>{{ field.label_tag }}</td>
        <td>{{ field }}</td>
      </tr>
      {% endfor %}
    </table>  
    <input type="submit" name="RegisterButton" value="Register Players" id="RegisterButton" />
    </form>
  <span class="normal">
    Registration for Basho ID {{ basho_id }}<br />
    {{ basho_full_name }}
  </span>
</body>

dewsweeper/boi/templates/boi/resultsindex.html
{% extends 'boi/base.html' %}
{% load static %}

{% block special_css %}
<link rel="stylesheet" type="text/css" href="{% static 'boi/resultsindex.css' %}" />
{% endblock %}

{% block head %}
  <title>Results - Basho of Imagination</title>
{% endblock %}

{% block content %}
<p class="header">Results</p>

{% for day in day_range %}
<a href="{% url 'boi:results' %}?b={{ basho_id }}&d={{ day }}" class="daylink">Day {{ day }}</a><br/><br/>
{% endfor %}

{% endblock %}

dewsweeper/boi/templates/boi/utils.html
{% extends 'boi/base.html' %}
{% load static %}

{% block special_css %}
<link rel="stylesheet" type="text/css" href="{% static 'boi/utils.css' %}" />
{% endblock %}

{% block head %}
  <title>Utilities - Basho of Imagination</title>
{% endblock %}

{% block content %}
<span class="title">Administrative Utilities</span><br /><br />
<a href="{% url 'boi:register_players' %}">Player Registration</a><br /><br />
<a href="{% url 'boi:record_banzuke' %}">Record Banzuke</a><br /><br />
<a href="{% url 'boi:waivers' %}">Waivers Utility</a><br /><br />
<a href="{% url 'boi:monkey_list' %}">Monkey List Generator</a><br /><br />
<a href="{% url 'boi:draft_registration' %}">Draft Registration</a><br /><br />
<a href="{% url 'boi:schedule_registration' %}">Schedule Tool</a><br /><br />
<a href="{% url 'boi:winlossmatrix' %}">Win/Loss Matrix</a><br /><br />
{% endblock %}